theme = "teoppuccin"
[editor]
auto-format = true
bufferline = "multiple"
color-modes = true
cursorline = true
end-of-line-diagnostics = "hint"
line-number = "relative"

[editor.file-picker]
git-ignore = true
hidden = false

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.lsp]
# display-inlay-hints = true
display-messages = true
display-progress-messages = true

[editor.soft-wrap]
enable = true

[keys.normal]
esc = ["keep_primary_selection", "collapse_selection"]
